export const CHANGE_CURRENT_SONG = "player/CHANGE_CURRENT_SONG"
export const CHANGE_PLAY_LIST = "player/CHANGE_PLAY_LIST"
export const CHANGE_CURRENT_SONG_INDEX = "player/CHANGE_CURRENT_SONG_INDEX"

export const CHANGE_PLAY_STRATEGY = "player/CHANGE_PLAY_STRATEGY"

export const CHANGE_LYRIC = "player/CHANGE_LYRIC"